// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yonzvqxnambgrhxkxsnv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlvbnp2cXhuYW1iZ3JoeGt4c252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYyNDUxODMsImV4cCI6MjA3MTgyMTE4M30.E2s3za86JHFmidzAUl1aw_3i2gerrL3bsGDiHQfY6zg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});